### ISSUE TITLE
Usability - grey out next button on first screen until a datasource is loaded

### ISSUE THREAD

**Issue by eileenmcnaughton** [saurabhbatra96/com.saurabhbatra96.civiimport#5]
I noticed that I can browse and find a file and then click 'next' without uploading it - which leaves me with a confusing empty screen on the next screen. I wonder about greying out the 'next' button until we have progressed to that screen

**Comment by eileenmcnaughton** [comment]
hmm - after tinkering I realise this is an ongoing issue - ie. I didn't realise I had to click on 'Use this mapping' before progressing to the next screen

**Comment by saurabhbatra96** [comment]
Going to leave this here, because TBH cannot find a more appropriate place for it.

In general: I've been kinda bogged down by a rather interesting but time consuming project on Operating Systems, forcing me to push back work on this extension. I've specifically bookmarked December for the same; a lot of the UX needs fixing/improving. I have been trying to stay involved, however indirectly, by helping a junior out wrt introduction to Civi; I'll introduce him to you once he feels confident enough to start solving some bugs.

In specific to this issue: I remember having a talk with Tim long long ago if it was possible to control the state of the "Next" button by validating form data. In short, it's not supported because the next button comes from `crm-ui-wizard` directive (if I'm not mistaken), which does not have access to the form inside. Maybe we can provide a specific method which can be called from the scope of the form... Or maybe I'll just pose this as a task for that junior before I make time for it in December.

An easier fix might just be to mention at the top, in bold: **Please click the Use Mapping button to proceed.** :)

**Comment by eileenmcnaughton** [comment]
Yeah - leave the quick fix for now - one day we'll get the right fix - probably patching crm-ui-wizard then?

**Comment by saurabhbatra96** [comment]
Yes, I do remember a few gists that Tim proposed, I'll have to get in touch with him again and have a quick discussion.

**Comment by eileenmcnaughton** [comment]
Well it would be good to at least find them & link them in here for later

**Comment by saurabhbatra96** [comment]
This PR to core: https://github.com/civicrm/civicrm-core/pull/9522
and commit: https://github.com/saurabhbatra96/com.saurabhbatra96.civiimport/commit/04122c2f35aa7e38c0e917abc54b2f8cdd611cb3 fixes.
